methods =  \
        [
        {'name':'statuses/user_timeline',
         'methods':['GET'],
         'limit':1,
         'requires_auth':'user_based',
         'response':{
             'object':'status',
             'cardinality':'n'},
         'parameters':[
             {
                 'name':'id',
                 'required':False},
             {   
                 'name':'user_id',
                 'required':False,
                 'type':'int'},
             {
                 'name':'count',
                 'required':False,
                 'type':'int',
                 'min':1,
                 'max':200},
             {
                 'name':'page',
                 'required':False,
                 'type':'int',
                 'min':1} ]
             },
        {'name':'users/show',
         'methods':['GET'],
         'requires_auth':'user_based',
         'response':{
             'object':'user',
             'cardinality':1},
         'parameters':[
             {
                 'name':'id',
                 'required':False},
             {   
                 'name':'user_id',
                 'required':False,
                 'type':'int'},
             {
                 'name':'screen_name',
                 'required':False} ]
             },
        {'name':'statuses/followers',
         'methods':['GET'],
         'requires_auth':True,
         'response':{
             'object':'user',
             'cardinality':'n'},
         'parameters':[
             {
                 'name':'id',
                 'required':False},
             {   
                 'name':'user_id',
                 'required':False,
                 'type':'int'},
             {
                 'name':'page',
                 'required':False,
                 'type':'int',
                 'min':1} ,
             {
                 'name':'screen_name',
                 'required':False} ]
             }
        ]  + \
	 [{'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['GET'],
	  'name': 'statuses/friends_timeline',
	  'parameters': [{'name': 'since_id', 'required': False},
					 {'name': 'max_id', 'required': False},
					 {'name': 'count', 'required': False},
					 ],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['GET'],
	  'name': 'statuses/mentions',
	  'parameters': [{'name': 'since_id', 'required': False},
					 {'name': 'max_id', 'required': False},
					 {'name': 'count', 'required': False},
					 {'name': 'page', 'required': False}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['GET'],
	  'name': 'statuses/show',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': False},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'statuses/update',
	  'parameters': [{'name': 'status', 'required': True},
					 {'name': 'in_reply_to_status_id', 'required': False}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['GET'],
	  'name': 'statuses/destroy',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['GET'],
	  'name': 'statuses/friends',
	  'parameters': [{'name': 'id', 'required': False},
					 {'name': 'user_id', 'required': False},
					 {'name': 'screen_name', 'required': False},
					 {'name': 'page', 'required': False}],
	  'requires_auth': False},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['GET'],
	  'name': 'direct_messages/sent',
	  'parameters': [{'name': 'since_id', 'required': False},
					 {'name': 'max_id', 'required': False},
					 {'name': 'page', 'required': False}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'direct_messages/new',
	  'parameters': [{'name': 'user:', 'required': True},
					 {'name': 'text', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST, DELETE'],
	  'name': 'direct_messages/destroy',
	  'parameters': [],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'friendships/create',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST, DELETE'],
	  'name': 'friendships/destroy',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '3',
	  'methods': ['GET'],
	  'name': 'friendships/exists',
	  'parameters': [{'name': 'user_a', 'required': True},
					 {'name': 'user_b', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'account/update_delivery_device',
	  'parameters': [{'name': 'device', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'account/update_profile_colors',
	  'parameters': [{'name': 'profile_background_color', 'required': False},
					 {'name': 'profile_text_color', 'required': False},
					 {'name': 'profile_link_color', 'required': False},
					 {'name': 'profile_sidebar_fill_color',
					  'required': False},
					 {'name': 'profile_sidebar_border_color',
					  'required': False}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '7',
	  'methods': ['POST'],
	  'name': 'account/update_profile_image',
	  'parameters': [{'name': 'image', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '8',
	  'methods': ['POST'],
	  'name': 'account/update_profile_background_image',
	  'parameters': [{'name': 'image', 'required': True},
					 {'name': 'tile', 'required': False}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '2',
	  'methods': ['POST'],
	  'name': 'account/update_profile',
	  'parameters': [{'name': 'name', 'required': False},
					 {'name': 'email', 'required': False},
					 {'name': 'url', 'required': False},
					 {'name': 'location', 'required': False},
					 {'name': 'description', 'required': False}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'favorites/create',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST, DELETE'],
	  'name': 'favorites/destroy',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'notifications/follow',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'notifications/leave',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST'],
	  'name': 'blocks/create',
	  'parameters': [],
	  'requires_auth': True},
	 {'baseurl': 'http://twitter.com/',
	  'limit': '1',
	  'methods': ['POST, DELETE'],
	  'name': 'blocks/destroy',
	  'parameters': [{'name': 'id', 'required': True}],
	  'requires_auth': True}]

